### PR TITLE
2to3

### PR DESCRIPTION
**Pull request by drhirsch**
Almost all working in Python 3. Need to deal with path to reliably import Fortran .so from Python 3. Does still work with Python2.7.

Also checks to see if already has kpap files, saving downloading each time it's installed.

### CODE REVIEW

**Comment by bharding512** [comment]
This is great. One question: does anyone know when Kp/Ap values become finalized? I know that for the DST index, it takes a couple years.

**Comment by timduly4** [comment]
Thanks for looking into this, Michael.  I would also be curious to know the
answer to Brian's question.

Tim

**Comment by butala** [comment]
Thank you for the contribution @drhirsch. 

I need to move some code to python3 and it would be nice to use pyglow. I saw your pull request but saw there are conflicts with bringing your contributions up to the current code. I took the liberty of essentially replicating your effort off the current code (using the futurize tools). This effort is encapsulated in the branch called python3. It's not a complete python3 port, but it works for my purposes. The remaining item is to either 1) hack in support for other platforms (OSX only for right now) or 2) move the build to completely fit into the distutils way of doing things (this is probably more trouble than it is worth).

**Comment by scivision** [comment]
No hacking required, setup.py can handle OS-independent builds of all the code including Fortran code. 
If @timduly4 would accept pull request, I can redo the changes for this, which I initially submitted about 3 years ago and reminded him about at Cedar 2017.

**Comment by timduly4** [comment]
I think we need to fix up the merge conflicts, first.

Thanks,
Tim

**Comment by bharding512** [comment]
+1 using Michael's setup.py

Just to make my comment from 3 years ago more explicit:

"massive savings in not redownloading files already held"

If we do this (and it's a good idea) then we should make the code smart enough to understand that these files are often updated over time, so we'll want to redownload them if they changed. (I admittedly haven't reviewed Michael's code, so not sure how this is implemented)

**Comment by timduly4** [comment]
How does this work?

**Comment by bharding512** [comment]
How does setup.py work? My limited understanding is that it's a platform-independent and more Python-esque replacement for the installation shell script (e.g.,, may allow pyglow to finally work on Windows).

**Comment by scivision** [comment]
setup.py is platform-independent. I even use it to compile program etc. 
There shouldn't be any reason offhand for this program not to work on Windows.

**Comment by scivision** [comment]
From my perspective, I have all these ionosphere/aurora/magnetosphere programs and many more on Github+PyPi as individual stand-alone, unit tested, fast, object-oriented, database-like / out-of-core memory enabled, working on Mac/Linux/Windows, so I didn't reform these commits. I.e. the Unix approach of a program doing one thing well

**Comment by scivision** [comment]
in a wry way, the fastest way to Pyglow 3 is to make a new repo with a setup.py that just calls all my standalone programs and you would have more of the simulataion program, with xarray.Dataset interfaces for database-like access with transparent read/write NetCDF4
;-)

**Comment by timduly4** [comment]
Hi Michael,

I'd prefer to keep the repository ongoing instead of starting from a new repository, that way it is easier to keep track of changes and understand how the program evolves with `git`.

If you'd like to make changes to `setup.py`, please make another PR and we can review.  I'd be interested to compile from `setup.py`.

Thanks,
Tim

**Pull request closed without merging**
