### PR TITLE
added profile class

### PR DESCRIPTION
**Pull request by aburrell**
Added a profile class, which speeds up running of iri when altitude
profiles are desired by more than a factor of 30.

### CODE REVIEW

**Comment by aburrell** [comment]
To test
----------

import datetime as dt
import timeit
import numpy as np
from pyglow import pyglow

nlons = 48
nlats = 60
dn = dt.datetime(1999, 3, 21)
lon_res = 7.5
lat_res = 3.0

lons = np.ones(shape=(nlons,nlats), dtype=float)
lats = np.ones(shape=(nlons,nlats), dtype=float)
alts = np.arange(80.0, 640.0, 10.0)
nalt = len(alts)

for ilon in range(nlons):
    lons[ilon,:] = ilon * lon_res
    lats[ilon,:] = np.arange(-90.0, 90.0, lat_res)

def run_prof():
    profs = np.ones(shape=(nlons, nlats), dtype=type(pyglow.Profile)) 
        for ilon in range(nlons):
            for ilat in range(nlats):
                profs[ilon,ilat] = pyglow.Profile(dn, lats[ilon,ilat], lons[ilon,ilat], alts[0], alts[-1], 10.0)               
                profs[ilon,ilat].run_iri(keep_workdir=False)              
    return profs

def run_points():
    points = np.ones(shape=(nlons, nlats, len(alts)), dtype=type(pyglow.Point))
    for ilon in range(nlons):
        for ilat in range(nlats):
            for ialt in range(nalt):
                points[ilon,ilat,ialt] = pyglow.Point(dn, lats[ilon,ilat], lons[ilon,ilat], alts[ialt])
                points[ilon,ilat,ialt].run_iri()
    return points

tprof = timeit.Timer('run_prof()', setup='from __main__ import run_prof')
tpoint = timeit.Timer('run_points()', setup='from __main__ import run_points')

tprof.timeit(number=3)
# Output for me was: 19.924533128738403

tpoint.timeit(number=3)
# Output for me will be updated when it's done

**Comment by timduly4** [comment]
@aburrell , my main concern with this code is that it repeats several methods of the Profile class.  So, if we made changes to one, we would have to remember to make changes to the other, and may result in problems / diverging methods down the road.

It is really important to make IRI run as fast as possible, so I appreciate this work.  

Maybe we could think about having the `Point` class inherit from `Profile`, thus making the `Point` class a special case of `Profile`?

**Comment by aburrell** [comment]
I absolutely agree with you, with respect to duplicate calls.  Making Point a special case of Profile should do the trick.  It may be worthwhile to merge this as a separate branch in pyglow so others can work on it?  I don’t have time at the moment because I’m across the Atlantic over the next month.  On the other hand, I’m happy to have a crack at doing this if no one cares about time sensitivity.  I’ll probably want to procrastinate productively sometime at the end of March.

Another thing that would be worthwhile to consider is moving the airglow model outside of Profile or Point, since the other model calls exist outside of either Profile or Points.  The airglow model in Profile can be run using numpy arrays or single points as input, so is pretty flexible.

Thoughts?

**Comment by timduly4** [comment]
@aburrell , the airglow methods may require a call to IRI and MSIS: 

https://github.com/timduly4/pyglow/blob/master/pyglow/pyglow.py#L478

I will merge this into pyglow's own `profile` branch for further development.

**Comment by aburrell** [comment]
Cheers!

**Pull request merged**
