### PR TITLE
User indices for IRI

### PR DESCRIPTION
**Pull request by timduly4**
If the user wants to input geophysical indices, then IRI will use `self.f107` and `self.f107a` when running IRI.

### CODE REVIEW

**Comment by timduly4** [comment]
@butala , thanks for your help on this-- your fix seemed to do the trick.

Can you please summarize what you did?  Your messages seem to have gotten lost within the merge, and it'd be great to have a record of what you did.

Note, I deleted these two lines from your patch, in order to prevent writing to stdout each time we call IRI:

```
	+1039a1041,1043
+>         write (*,*) "f107d",f107d,"f107y",f107y
+>         write (*,*) "f10781",f10781,"f107365",f107365
```

Now, after the tests show that inputting user indices does indeed change the electron density:

```
~/pyglow/tests $ ./test_user_indices.py 

pyglow version = 1.1
Testing user defined indices in IRI:
------- ---- ------- ------- -- ----
Using default F10.7:
f10.7 = 125.60
f10.7a = 160.55
ne = 361218.21

Using user defined F10.7:
f10.7 = 200.00
f10.7a = 200.00
ne = 363029.59

Using user defined F10.7:
f10.7 = 125.60
f10.7a = 160.55
ne = 360263.09
```

Again, thanks for the help!

**Comment by butala** [comment]
Hey Tim,

The fix involved deciphering the control flow in IRI16 and noticing that the use of the user F107 index was skipped whenever IRISUB is called more than once. Resetting the global state to avoid this caused a major slowdown (all tables and whatnot were then reinitialized on each call to IRISUB). The patch moves the branch point of an it statement to be prior to the F107 index setup code.

It’s a hack but it works.

And it really is totally a hack. I made a similar adjustment to IRI12 and the fix does not work! I can confirm that appropriate F107 related variables are set, but it seems to make no difference to the output Ne. I tried resetting the global state on each call, but still the same incorrect (the output Ne has to be a function of F107) behavior. I am totally at a loss!

Given what I just said, I am very hesitant to put a stamp of approval on what I have done. You have been warned :). Maybe have the code fail when version==2012?

I have not received a response from Bilitza on this matter, not that I really expected it.

—
- Mark

On Mar 16, 2018, at 05:13, Timothy Duly <notifications@github.com<mailto:notifications@github.com>> wrote:


@butala<https://github.com/butala> , thanks for your help on this-- your fix seemed to do the trick.

Can you please summarize what you did? Your messages seem to have gotten lost within the merge, and it'd be great to have a record of what you did.

Note, I deleted these two lines from your patch, in order to prevent writing to stdout each time we call IRI:

        +1039a1041,1043
+>         write (*,*) "f107d",f107d,"f107y",f107y
+>         write (*,*) "f10781",f10781,"f107365",f107365


Now, after the tests show that inputting user indices does indeed change the electron density:

~/pyglow/tests $ ./test_user_indices.py

pyglow version = 1.1
Testing user defined indices in IRI:
------- ---- ------- ------- -- ----
Using default F10.7:
f10.7 = 125.60
f10.7a = 160.55
ne = 361218.21

Using user defined F10.7:
f10.7 = 200.00
f10.7a = 200.00
ne = 363029.59

Using user defined F10.7:
f10.7 = 125.60
f10.7a = 160.55
ne = 360263.09


Again, thanks for the help!

**Comment by butala** [comment]
OK --- I think this is in now.

**Comment by timduly4** [comment]
@butala thanks again for your help & comments.

We haven't merged this in, yet, so I re-opened.

Let me merge in the changes, then we can close.

**Comment by butala** [comment]
I may have screwed something up then — from my history it like this had merged.

On Mar 19, 2018, at 21:45, Timothy Duly <notifications@github.com<mailto:notifications@github.com>> wrote:


@butala<https://github.com/butala> thanks again for your help & comments.

We haven't merged this in, yet, so I re-opened.

Let me merge in the changes, then we can close.

**Pull request merged**
